---
title: Event Site - a Jekyll template by BowTie.io
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  events:
    title: Events
    output: true
  logos:
    title: Logos
    output: false
  organizers:
    title: Organizers
    output: false
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: false
  sections:
    title: Sections
    output: false
  speakers:
    title: Speakers
    output: false
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
description: 'Build a simple Event site without writing code. The BowTie collection
  editor makes it easy to build sites, blogs, or static apps that you can hand off
  to clients.

'
email: info@example.com
logourl: "/img/logo.png"
author: Your Name
author_thumbnail: "/img/user1.png"
google_analytics_id: 
theme:
  contact:
    company: Company Name
    address: 2420 17th St
    city: Denver
    state: CO
    zip: 80202
    country: USA
    phone: 555-123-4567
    latlng: 39.7584972,-105.0077574,20.25z
    twitter: twitter
    facebook: facebook
    github: 
    instagram: 
    flickr: 
    linkedin: 
    youtube: 
  disqus_id: bowtieexample
  addthis_id: 
permalink: "/:categories/:title/"
relative_permalinks: false
gems:
- jekyll-paginate
paginate: 5
paginate_path: "/page/:num"
include: []
keep_files: []
exclude:
- ".gitignore"
- ".sass-cache"
